# core/models.py
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enums – shared across core
# ---------------------------------------------------------------------------

class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


# ---------------------------------------------------------------------------
# Candle – one OHLCV bar
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Candle:
    """
    Generic OHLCV candle used across the system.

    This is deliberately independent from pandas/Binance types.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    extra: dict[str, float] = field(default_factory=dict)  # e.g. {"ATR": 0.0123, "RSI_14": 55.0}

# ---------------------------------------------------------------------------
# Order – representation of an order in our domain
# ---------------------------------------------------------------------------

@dataclass
class Order:
    """
    Domain order model, independent from any exchange-specific schema.

    id:
        Internal ID generated by our system (not Binance's orderId).
    """
    id: str
    symbol: str           # e.g. "XRPUSDT"
    side: Side            # BUY or SELL
    price: float          # For LIMIT/STOP_LIMIT; can be 0.0 for MARKET
    qty: float            # Base-asset quantity
    type: OrderType       # LIMIT / MARKET / STOP / STOP_LIMIT

    created_at: datetime = field(default_factory=datetime.utcnow)

    # Optional fields for later use (not in acceptance criteria but useful)
    client_tag: Optional[str] = None      # e.g. "grid_1_level_3"
    is_active: bool = True                # False once fully filled or cancelled


# ---------------------------------------------------------------------------
# Position – open or closed trade position
# ---------------------------------------------------------------------------

@dataclass
class Position:
    """
    Represents an open or closed position resulting from one or more orders.
    """
    id: str
    symbol: str
    side: PositionSide      # LONG / SHORT
    entry_price: float
    size: float             # Positive number, sign is implied by side
    opened_at: datetime
    closed_at: Optional[datetime] = None

    # Optional bookkeeping fields
    realized_pnl: float = 0.0
    fees_paid: float = 0.0

    @property
    def is_open(self) -> bool:
        return self.closed_at is None


# ---------------------------------------------------------------------------
# AccountState – snapshot of account-level balances
# ---------------------------------------------------------------------------
@dataclass
class AccountState:
    """
    Minimal account snapshot used by risk management and backtests.
    All values are in quote currency (e.g. USDT or EUR).
    """
    cash_balance: float        # real cash in wallet
    total_value: float         # cash + market value of all positions
    invested_cost: float       # total cost basis of open positions

    @property
    def available_cash(self) -> float:
        """How much I can actually spend right now in spot."""
        return self.cash_balance

    @property
    def free_equity(self) -> float:
        """
        Equity not tied up as cost in open positions.
        Useful if you *later* want a margin-like or risk-based view.
        """
        return self.total_value - self.invested_cost



# ---------------------------------------------------------------------------
# Events – used by backtest engine & strategy to communicate fills
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class OrderFilledEvent:
    """
    Domain event: an order (or part of it) has been filled.

    This is what the backtest engine emits and the strategy / grid engine
    listens to, instead of dealing with raw exchange responses.
    """
    order_id: str
    symbol: str
    side: Side
    price: float
    qty: float
    filled_at: datetime

    position_id: Optional[str] = None  # The position this fill belongs to (if any)
