# core/models.py
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enums – shared across core
# ---------------------------------------------------------------------------

class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


# ---------------------------------------------------------------------------
# Candle – generic OHLCV
# ---------------------------------------------------------------------------

@dataclass
class Candle:
    """
    Generic OHLCV candle used across the system.
    This is deliberately independent from pandas/Binance types.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    # Indicator values or other enrichments are attached here.
    extra: dict[str, float] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Order – representation of an order in our domain
# ---------------------------------------------------------------------------

@dataclass
class Order:
    """
    Domain order model, independent from any exchange-specific schema.

    id:
        Internal ID generated by our system (not Binance's orderId).
        In the cleaned architecture, the ENGINE is the single authority
        for assigning order IDs (e.g. "XRPUSDT-123").
    """
    id: str
    symbol: str           # e.g. "XRPUSDT"
    side: Side            # BUY or SELL
    price: float          # For LIMIT/STOP_LIMIT; can be 0.0 for MARKET
    qty: float            # Base-asset quantity
    type: OrderType       # LIMIT / MARKET / STOP / STOP_LIMIT

    created_at: datetime = field(default_factory=datetime.utcnow)

    # Optional fields
    client_tag: Optional[str] = None      # e.g. "XRPUSDT:LVL:7"
    is_active: bool = True                # False once filled/cancelled


# ---------------------------------------------------------------------------
# Position – open or closed trade position
# ---------------------------------------------------------------------------

@dataclass
class Position:
    """
    Represents an open or closed position resulting from one or more orders.
    """
    id: str
    symbol: str
    side: PositionSide      # LONG / SHORT
    entry_price: float
    size: float             # Positive number, sign is implied by side
    opened_at: datetime

    closed_at: Optional[datetime] = None
    realized_pnl: float = 0.0
    fees_paid: float = 0.0

    @property
    def is_open(self) -> bool:
        return self.closed_at is None


# ---------------------------------------------------------------------------
# AccountState – snapshot of account-level balances
# ---------------------------------------------------------------------------

@dataclass
class AccountState:
    """
    Minimal account snapshot used by risk management and backtests.
    All values are in quote currency (e.g. USDT).
    """
    cash_balance: float
    total_value: float
    invested_cost: float

    @property
    def unrealized_pnl(self) -> float:
        """
        Unrealized PnL is total_value - invested_cost.
        """
        return self.total_value - self.invested_cost


# ---------------------------------------------------------------------------
# Events – used by backtest engine & strategy to communicate fills
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class OrderFilledEvent:
    """
    Domain event: an order (or part of it) has been filled.

    This is what the backtest engine emits and the strategy / grid engine
    listens to, instead of dealing with raw exchange responses.
    """
    order_id: str
    symbol: str
    side: Side
    price: float
    qty: float
    filled_at: datetime

    # NEW: propagate Order.client_tag to the strategy.
    # This allows strategies to map fills back to grid levels even though
    # the engine assigns the final order_id later.
    client_tag: Optional[str] = None

    position_id: Optional[str] = None
